title: placeholder.txt
description: Repository of all things midly interesting.
author: Ethan Mui
logo: static/img/avatar.png
github: https://github.com/pyramidian
about: Mechanical Engineering Student at RIT

baseurl: ""
url: "https://pyramidian.github.io/College-Blog-v1.0"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
